number_of_penguins = input()
print('     ~      '  * int(number_of_penguins))
print('   (o o)    ' * int(number_of_penguins))
print(' /   V   \  '  * int(number_of_penguins))
print('/ (  _  ) \ ' * int(number_of_penguins))
print('   ^^ ^^    ' * int(number_of_penguins))
